//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int ID_Rental { get; set; }
        public Nullable<int> Car_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public System.DateTime RentalDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
